# Generated by Django 3.0.3 on 2020-03-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20200310_1507'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='restaurant',
        #     name='close_time',
        #     field=models.TimeField(default=0),
        # ),
    ]
