# Generated by Django 3.0.3 on 2020-03-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20200311_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='count',
            field=models.IntegerField(default=0),
        )
    ]
