# Generated by Django 3.0.3 on 2020-03-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='is_vegan',
            field=models.BooleanField(default=False),
        ),
    ]
