# Generated by Django 3.0.3 on 2020-03-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20200310_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='f_picture',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
